### ISSUE TITLE
Not all emojis can be detected

### ISSUE THREAD

**Issue by makbeth** [aksafan/yii2-emoji-detection#1]
For example this 🤠 can be detected, but this 🦾 not.

**Comment by aksafan** [comment]
Hello @makbeth 
This happened cause of old version of the original library I've used for mine. Will try to ask that library's author to update it. In case, he'd not answer I will refactor and update mine.

**Comment by aksafan** [comment]
Hey @makbeth 
I didn't get answer from the author of original library so made a fork and do all needed things to update map for emoji. So now you can use fully updated library starting with 1.2.0 release - https://github.com/aksafan/yii2-emoji-detection/releases/tag/1.2.0

P.S: Updated emoji database to Jan 2020 version and wrote a test for your emoji 🦾 - https://github.com/aksafan/yii2-emoji-detection/blob/master/tests/DetectAllTests.php#L150

Cheers
